.\" Manpage for kzorp.
.\" Contact zorp@balabit.hu to correct errors or typos.
.TH man 8 "15 Dec 2013" "1.0" "kzorp man page"
.SH NAME
kzorp \- manage zorp's packet filter rules
.SH SYNOPSIS
kzorp [options]
.SH DESCRIPTION
kzorp is used to manage zones, services, dispatchers and instance bind parameters
.SH OPTIONS
.TP
\fB\-\-help\fR
Displays a help about the usage of kzorp. See the other options there.
.SH SEE ALSO
the ooutput of kzorp --help
.SH BUGS
No known bugs.
.SH AUTHOR
Balabit Zorp team (zorp@balabit.hu)

