
#gcc -Wp,-MMD,./.libxt_CLASSIFY.oo.d,-MT,libxt_CLASSIFY.oo -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 	-D_REENTRANT -Wall -Waggregate-return -Wmissing-declarations 	-Wmissing-prototypes -Wredundant-decls -Wshadow -Wstrict-prototypes 	-Winline -pipe 	-DXTABLES_LIBDIR=\"/usr/local/libexec/xtables\" -DXTABLES_INTERNAL -I../include -I../include  -D_INIT=libxt_CLASSIFY_init -DPIC -fPIC -g -O2 -o libxt_CLASSIFY.oo -c libxt_CLASSIFY.c;
#gcc  -shared  -o libxt_CLASSIFY.so libxt_CLASSIFY.oo;

XTABLES_LIBDIR="/lib/xtables"
CFLAGS= -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64   -D_REENTRANT -Wall -Wextra -DXTABLES_LIBDIR=$(XTABLES_LIBDIR) -DXTABLES_INTERNAL -I../include -I../include -DPIC -fPIC -g -O2

