#
# This file is generated by Zorp Management System. Do not edit!
#

from  Zorp.Core import  *
from  Zorp.Proxy import  *
from  Zorp.Plug import  *

"""Fallback zone"""
InetZone('internet', ['0.0.0.0/0'],
    inbound_services=["*"],
    outbound_services=["*"])

InetZone('enternet', ['1.2.3.4/16'],
    inbound_services=[
        "service", "pfservice"],
    outbound_services=[
        "service", "pfservice"])

def generate_rules():
    gen_rules = []
    for i in range(100000):
        gen_rules.append({ 'iface': ("eth0", "eth1"), 'ifgroup': (2, 9), 'proto': socket.IPPROTO_TCP, 'src_port': 80, 'dst_port': "12,23:24",
          'src_subnet': ('10.0.0.0/8', '1.2.3.5/24'), 'src_zone': ('internet', 'internet'),
          'dst_subnet': '2.3.4.5', 'dst_zone': 'internet', 'service': 'pityuka'})

    NDimensionDispatcher(bindto=DBSockAddr(SockAddrInet('0.0.0.0', 50000), ZD_PROTO_TCP), rules=tuple(gen_rules))

def plug() :
    PFService(name="pityuka", router=TransparentRouter(forge_addr=TRUE))
    generate_rules()
