#!/bin/bash
# run it as root
# actually zorpnternet is in its netns
brctl addbr zorpintranet
ip netns add zorpinternet
ip netns exec zorpinternet brctl addbr zorpinternet
ifconfig zorpintranet 11.22.33.1 netmask 255.255.255.0 broadcast 11.22.33.255
ip netns exec zorpinternet ifconfig zorpinternet 44.55.66.253 netmask 255.255.255.252 broadcast 44.55.66.255
echo -e "\nallow zorpinternet\nallow zorpintranet" >>/etc/qemu/bridge.conf

