#!/bin/bash

#set -x
KVERS=$1
ZORPROOT=~/zwa/install/zorp-3.5
#KVERS=3.5.0-26-generic
tmpdir=`mktemp -d`
mydir=`dirname $BASH_SOURCE`
SRCDIR=`readlink -f $mydir`
DESTDIR=$tmpdir/initrd
DKMSDIR=$tmpdir/initrd/lib/modules/$KVERS/updates/dkms
. /usr/share/initramfs-tools/hook-functions
mkdir $tmpdir/initrd
cd $tmpdir/initrd
gzip -d </boot/initrd.img-$KVERS | cpio --quiet -idmu
find /lib/modules/$KVERS/kernel/net | cpio --unconditional --quiet -p .
mkdir -p $DKMSDIR
cp $SRCDIR/../*.ko $DKMSDIR
depmod -a -b $tmpdir/initrd -F /boot/System.map-$KVERS $KVERS
cp $SRCDIR/initrd/* conf
cd $DESTDIR ;dpkg -L libc6 iptables |egrep -v "^$" |cpio --unconditional --quiet -p .
copy_exec /usr/sbin/mz
copy_exec /sbin/ip
copy_exec /bin/nc
copy_exec /usr/sbin/tcpdump
copy_exec /usr/bin/python2.7
copy_exec /usr/bin/lsof
copy_exec /usr/bin/env
copy_exec /bin/chown
#dpkg -L python-openssl coreutils python-radix python-minimal iptables python-support python python2.7 python2.7-minimal python-dns |egrep -v "^$|^/etc/zorp" |cpio --unconditional --quiet -p .
copy_exec $ZORPROOT/lib/zorp/zorp 
cd $ZORPROOT ; find | cpio --unconditional --make-directories --quiet -p $DESTDIR
cd $DESTDIR/$ZORPROOT ; find | cpio --unconditional --make-directories --quiet -p $DESTDIR
rm -rf $DESTDIR/$ZORPROOT
mkdir -p $DESTDIR/`dirname $ZORPROOT`
ln -s / $DESTDIR/$ZORPROOT
cd $DESTDIR; find |cpio --quiet -R 0:0 -o -H newc |gzip >../initrd.img
sudo kvm -m 2G -nographic -initrd $tmpdir/initrd.img -kernel /boot/vmlinuz-$KVERS -append console=ttyS0,115200 \
	-net nic,vlan=0 -net bridge,vlan=0,br=zorpintranet \
	-net nic,vlan=1 -net bridge,vlan=1,br=zorpinternet,helper=$SRCDIR/helper >/tmp/out&
thepid=$!
cd $SRCDIR;
if ./exerciser
then
	echo KVM TEST OK
else
	echo KVM TEST FAILED
fi
sudo kill $thepid
rm -rf $tmpdir
./outtest


#kvm -m 2G -nographic -initrd /tmp/TESTROOT/initrd.img -kernel /boot/vmlinuz-3.2.35 -append console=ttyS0,115200 \
#	-net nic,vlan=0 -net user,vlan=0,net=11.22.33.0/24,guestfwd=tcp:11.22.33.1:1234-tcp:127.0.0.1:9999,hostfwd=tcp:127.0.0.1:10000-11.22.33.10:8888\
#	-net nic,vlan=1 -net user,vlan=1,net=44.55.66.0/24,guestfwd=tcp:44.55.66.253:8888-tcp:127.0.0.1:10001


