#!/bin/bash

#set -x
KVERS=$1
mydir=`dirname $BASH_SOURCE`
SRCDIR=`readlink -f $mydir`
tmpdir=$SRCDIR/testimgs/$KVERS
exec sudo kvm -m 2G -nographic -initrd $tmpdir/initrd.img -kernel /boot/vmlinuz-$KVERS -append console=ttyS0,115200 \
	-net nic,vlan=0 -net bridge,vlan=0,br=zorpintranet \
	-net nic,vlan=1 -net bridge,vlan=1,br=zorpinternet,helper=$SRCDIR/helper 

