#!/bin/bash

set -x
KVERS=$1
#ZORPROOT=~/zwa/install/zorp-3.5
#KVERS=3.5.0-26-generic
mydir=`dirname $BASH_SOURCE`
SRCDIR=`readlink -f $mydir`
packagedir=`dirname $SRCDIR`
kernmoddir=$packagedir/kernel-module
pylibdir=$packagedir/pylib
tmpdir=$SRCDIR/testimgs/$KVERS
DESTDIR=$tmpdir/initrd
DKMSDIR=$tmpdir/initrd/lib/modules/$KVERS/updates/dkms
. /usr/share/initramfs-tools/hook-functions
mkdir -p $tmpdir/initrd
cd $tmpdir/initrd
gzip -d </boot/initrd.img-$KVERS | cpio --quiet -idmu
find /lib/modules/$KVERS/kernel/net | cpio --unconditional --quiet -p .
mkdir -p $DKMSDIR
cp $kernmoddir/*.ko $DKMSDIR
sudo chmod a+r /boot/System.map-$KVERS
depmod -a -b $tmpdir/initrd -F /boot/System.map-$KVERS $KVERS
cp $SRCDIR/initrd/* conf
cd $DESTDIR ;dpkg -L libc6 iptables |egrep -v "^$" |cpio --unconditional --quiet -p .
set +x
copy_exec /usr/sbin/mz
copy_exec /sbin/ip
copy_exec /bin/nc
copy_exec /usr/sbin/tcpdump
copy_exec /usr/bin/python2.7
copy_exec /usr/bin/lsof
copy_exec /usr/bin/env
copy_exec /bin/chown
set -x
dpkg -L python-openssl coreutils python-minimal iptables python-support python python2.7 python2.7-minimal |egrep -v "^$|^/etc/zorp" |cpio --unconditional --quiet -p .
#copy_exec $ZORPROOT/lib/zorp/zorp 
#cd $ZORPROOT ; find | cpio --unconditional --make-directories --quiet -p $DESTDIR
#cd $DESTDIR/$ZORPROOT ; find | cpio --unconditional --make-directories --quiet -p $DESTDIR
#rm -rf $DESTDIR/$ZORPROOT
#mkdir -p $DESTDIR/`dirname $ZORPROOT`
#ln -s / $DESTDIR/$ZORPROOT
cp -r $pylibdir/kzorp/kzorp $DESTDIR/usr/lib/python2.7/dist-packages
cp $pylibdir/kzorp/kzorp.py $DESTDIR/usr/sbin/kzorp
cd $DESTDIR; find |cpio --quiet -R 0:0 -o -H newc |gzip >../initrd.img

exit 0

