#!/bin/bash

#set -x
KVERS=$1
mydir=`dirname $BASH_SOURCE`
SRCDIR=`readlink -f $mydir`
tmpdir=$SRCDIR/testimgs/$KVERS
cd $SRCDIR;
./imgrun $KVERS >$tmpdir/out &
thepid=$!
if ./exerciser 
then
	echo KVM TEST OK
else
	echo KVM TEST FAILED
fi
sudo kill $thepid
./outtest $tmpdir/out



